### ISSUE TITLE
USER STORY: DATA - Collect Project Info

### ISSUE THREAD

**Issue by JesseCaddell** [SeattleColleges/SeattleColleges.github.io#3]
As a dev, I want to collect all of the data required for the App Dev programs current applications in development.

### Applications and data to be collected
**Belinda's Closet**
Product Owner: Keiffer

- [x] Title
- [x] Screenshots
- [x] Video || In progress
- [x] About || Placeholder
- [x] Live Demo || In progress
- [x] Github

**NSC Events**
Product Owner: Hanan 

- [x] Title
- [x] Screenshots
- [x] Video || Waiting on links
- [x] About
- [x] Live Demo || Waiting on links
- [x] Github

**Pelletier Construction**
Product Owner: Taylor Papke

- [x] Title
- [x] Screenshots || Placeholder
- [x] Video || Won't be ready for awhile
- [x] About || Placeholder
- [x] Live Demo || Won't be ready for awhile
- [x] Github

### NOTES

- Pelletier will not be ready for the launch of the website.

**Comment by nickolasram** [comment]
@JesseCaddell Can you commit what you have so far, with null values for any missing fields, and create a pull request? You can continue to work on this after. It would just be helpful to have some data to work with while styling.
