### ISSUE TITLE
Figma Collaboration: Create account and share email

### ISSUE THREAD

**Issue by nickolasram** [SeattleColleges/SeattleColleges.github.io#7]
If you wish to work on the figma design, make sure to sign up for an account and share the email you used so we can collab. I'll create a slack thread in the practicums and capstones channel where we can post our emails tomorrow afternoon.

**Comment by nickolasram** [comment]
@BradleyCharles and I have shared emails on slack. I started a project, but I asked them to start a new one since I'm limited to free features.

**Comment by BradleyCharles** [comment]
Sorry I had been slacking on this but I sent an invite to you Cameron. If anyone else needs access you should be able to use this link https://www.figma.com/team_invite/redeem/qFwLiyJLxqWBszT9noqSKw

**Comment by nickolasram** [comment]
Closing this issue because the project was started last week and we’ve been working on it
